import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export const metadata = {
  title: 'Legal — EdgeScan',
  description: 'Terms of Service, Privacy Policy, Financial Disclaimer, and Refund Policy for EdgeScan.',
}

function LegalSection({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mb-10 scroll-mt-8">
      <h2 className="text-xl font-semibold text-[var(--text)] mb-4 pb-2 border-b border-[var(--border)]">
        {title}
      </h2>
      <div className="space-y-3 text-sm text-[var(--text-muted)] leading-relaxed">
        {children}
      </div>
    </section>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p>{children}</p>
}

export default function LegalPage() {
  const lastUpdated = 'June 2026'

  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <Link
        href="/scanner"
        className="inline-flex items-center gap-1.5 text-sm text-[var(--text-muted)] hover:text-[var(--text)] mb-8 transition-colors"
      >
        <ArrowLeft className="h-4 w-4" />
        Back
      </Link>

      <h1 className="text-3xl font-bold text-[var(--text)] mb-2">Legal</h1>
      <p className="text-[var(--text-muted)] text-sm mb-8">Last updated: {lastUpdated}</p>

      {/* TOC */}
      <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4 mb-10">
        <p className="text-xs font-semibold text-[var(--text-muted)] uppercase tracking-wide mb-3">Contents</p>
        <ol className="space-y-1.5 text-sm">
          {[
            ['#disclaimer', 'Financial Disclaimer'],
            ['#terms', 'Terms of Service'],
            ['#privacy', 'Privacy Policy'],
            ['#refund', 'Refund Policy'],
          ].map(([href, label]) => (
            <li key={href}>
              <Link href={href} className="text-[var(--accent)] hover:underline">
                {label}
              </Link>
            </li>
          ))}
        </ol>
      </div>

      <LegalSection id="disclaimer" title="Financial Disclaimer">
        <P>
          EdgeScan is a financial data and analytics platform. All content, including stock scores,
          price targets, AI-generated theses, signals, and commentary, is provided for{' '}
          <strong className="text-[var(--text)]">informational purposes only</strong> and does not
          constitute personalised investment advice, a solicitation to buy or sell securities, or a
          recommendation to engage in any investment strategy.
        </P>
        <P>
          EdgeScan is <strong className="text-[var(--text)]">not a registered investment adviser</strong>,
          broker-dealer, or financial planner. The scores and outputs are generated by algorithmic
          models and AI systems that may contain errors, omissions, or outdated information.
          Algorithmic scores do not account for your individual financial situation, risk tolerance,
          investment objectives, or tax circumstances.
        </P>
        <P>
          <strong className="text-[var(--text)]">Past performance is no guarantee of future results.</strong>{' '}
          Markets can move against model predictions. You may lose some or all of any capital you
          invest based on information from this platform.
        </P>
        <P>
          Always consult a qualified, licensed financial adviser before making any investment decision.
          EdgeScan and its operators accept no liability for financial losses incurred as a result of
          relying on content provided by this service.
        </P>
      </LegalSection>

      <LegalSection id="terms" title="Terms of Service">
        <P>
          By accessing or using EdgeScan (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of
          Service. If you do not agree, do not use the Service.
        </P>
        <P>
          <strong className="text-[var(--text)]">Acceptable use.</strong> You may use EdgeScan for
          personal, non-commercial research purposes. You may not scrape, redistribute, resell, or
          sublicense data obtained from EdgeScan. Automated access beyond normal browser use requires
          prior written permission.
        </P>
        <P>
          <strong className="text-[var(--text)]">Accounts.</strong> You are responsible for maintaining
          the confidentiality of your login credentials. You must be at least 18 years old to create
          an account. We reserve the right to suspend or terminate accounts that violate these terms.
        </P>
        <P>
          <strong className="text-[var(--text)]">Pro subscription.</strong> Pro features are available
          to paid subscribers. Subscription terms, pricing, and cancellation are governed by your
          agreement with Stripe, our payment processor.
        </P>
        <P>
          <strong className="text-[var(--text)]">Intellectual property.</strong> The EdgeScan scoring
          methodology, software, and design are proprietary. You may not copy or replicate the Service
          without permission.
        </P>
        <P>
          <strong className="text-[var(--text)]">Limitation of liability.</strong> To the maximum extent
          permitted by law, EdgeScan and its operators shall not be liable for any direct, indirect,
          incidental, or consequential damages arising from use of the Service. The Service is provided
          &ldquo;as is&rdquo; without warranties of any kind.
        </P>
        <P>
          <strong className="text-[var(--text)]">Changes to terms.</strong> We may update these terms
          at any time. Continued use of the Service after changes constitutes acceptance of the
          revised terms.
        </P>
      </LegalSection>

      <LegalSection id="privacy" title="Privacy Policy">
        <P>
          We collect the following information to provide the Service:
        </P>
        <ul className="list-disc pl-5 space-y-1">
          <li>Email address and name provided at registration</li>
          <li>Google account ID and profile picture (Google OAuth users only)</li>
          <li>Watchlist tickers and portfolio holdings you create</li>
          <li>Subscription status (managed by Stripe — we do not store card details)</li>
          <li>Server logs (IP address, timestamp, request path) for security and debugging</li>
        </ul>
        <P>
          <strong className="text-[var(--text)]">How we use your data.</strong> We use your email to
          send verification, password-reset, and transactional emails. We do not sell or share your
          personal data with third parties for marketing purposes.
        </P>
        <P>
          <strong className="text-[var(--text)]">Third-party processors.</strong> We use Stripe for
          payment processing (their privacy policy applies to billing data), Anthropic for AI thesis
          generation (prompts contain only ticker symbols and financial metrics — no personal data),
          and a transactional email provider for account emails.
        </P>
        <P>
          <strong className="text-[var(--text)]">Data retention.</strong> Active account data is
          retained while your account exists. Server logs are retained for 90 days. Billing records
          are retained as required by applicable law.
        </P>
        <P>
          <strong className="text-[var(--text)]">Your rights.</strong> You may delete your account at
          any time from the Account Settings page. Deletion anonymises your personal data (email,
          name, Google ID) while retaining anonymised billing records for legal compliance. You may
          request a data export by contacting us.
        </P>
        <P>
          <strong className="text-[var(--text)]">Cookies.</strong> We use a single httpOnly session
          cookie (&ldquo;authjs.session-token&rdquo;) to maintain your login state. No third-party tracking or
          advertising cookies are set.
        </P>
      </LegalSection>

      <LegalSection id="refund" title="Refund Policy">
        <P>
          <strong className="text-[var(--text)]">Monthly plans.</strong> Monthly subscriptions are
          non-refundable. You may cancel at any time; your Pro access continues until the end of the
          current billing period, after which your account reverts to the Free plan.
        </P>
        <P>
          <strong className="text-[var(--text)]">Annual plans.</strong> Annual subscriptions are
          eligible for a full refund within 14 days of purchase if you have not made significant use
          of Pro features. Refund requests after 14 days are evaluated on a case-by-case basis.
        </P>
        <P>
          <strong className="text-[var(--text)]">How to request a refund.</strong> Contact us at the
          email address on your Stripe receipt, or manage your subscription via the Stripe Customer
          Portal (accessible from your Account Settings). Refunds are processed within 5–10 business
          days to your original payment method.
        </P>
        <P>
          <strong className="text-[var(--text)]">Service interruptions.</strong> If EdgeScan is
          unavailable for a sustained period (&gt;24 hours) due to our error, Pro subscribers may
          request a pro-rated credit. We do not offer refunds for scheduled maintenance or events
          beyond our reasonable control.
        </P>
      </LegalSection>
    </div>
  )
}
